inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/bundle/**/*'

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/ExampleLength:
  Max: 7

RSpec/MessageSpies:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
