inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require:
  - rubocop-rspec

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/ExampleLength:
  Max: 7

RSpec/MultipleMemoizedHelpers:
  Enabled: false
