name: RSpec test suite

on: [push]

jobs:
  ruby:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install RubyGems
      run: |
        gem install bundler --no-doc
        bundle config path vendor/bundle
        bundle check || bundle install

    - name: Run Specs
      run: |
        bundle exec rspec
